//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
  SvrCh_BDINT : STRUCT
    pMeth : ^CHMETH;
    dData : BDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_BDINT : STRUCT
    pCh : ^SvrCh_BDINT;
    dData : BDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_DINT : STRUCT
    pMeth : ^CHMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_DINT : STRUCT
    pCh : ^SvrCh_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_gpt_LogData : STRUCT
    pMeth : ^CHMETH;
    dData : gpt_LogData;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_gpt_LogData : STRUCT
    pCh : ^SvrCh_gpt_LogData;
    dData : gpt_LogData;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_gt_AgvMainAuto : STRUCT
    pMeth : ^CHMETH;
    dData : gt_AgvMainAuto;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_gt_AgvMainAuto : STRUCT
    pCh : ^SvrCh_gt_AgvMainAuto;
    dData : gt_AgvMainAuto;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_gt_AgvMainAux : STRUCT
    pMeth : ^CHMETH;
    dData : gt_AgvMainAux;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_gt_AgvMainAux : STRUCT
    pCh : ^SvrCh_gt_AgvMainAux;
    dData : gt_AgvMainAux;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_gt_agvMainPeripherals : STRUCT
    pMeth : ^CHMETH;
    dData : gt_agvMainPeripherals;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_gt_agvMainPeripherals : STRUCT
    pCh : ^SvrCh_gt_agvMainPeripherals;
    dData : gt_agvMainPeripherals;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_gt_AgvManual : STRUCT
    pMeth : ^CHMETH;
    dData : gt_AgvManual;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_gt_AgvManual : STRUCT
    pCh : ^SvrCh_gt_AgvManual;
    dData : gt_AgvManual;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_gt_AgvSettingsCmd : STRUCT
    pMeth : ^CHMETH;
    dData : gt_AgvSettingsCmd;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_gt_AgvSettingsCmd : STRUCT
    pCh : ^SvrCh_gt_AgvSettingsCmd;
    dData : gt_AgvSettingsCmd;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_UDINT : STRUCT
    pMeth : ^CHMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_UDINT : STRUCT
    pCh : ^SvrCh_UDINT;
    dData : UDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrChCmd_DINT : STRUCT
    pMeth : ^CMDMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__CheckSum : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_CheckSum;
  END_STRUCT;
  CltChCmd__cJSON : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_cJSON;
  END_STRUCT;
  CltChCmd__ComLogging : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_ComLogging;
  END_STRUCT;
  CltChCmd__FileSys : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_FileSys;
  END_STRUCT;
  CltChCmd__JSONReader : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_JSONReader;
  END_STRUCT;
  CltChCmd__JSONWriter : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_JSONWriter;
  END_STRUCT;
  SvrChCmd_UDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__MemoryBubbles : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^_MemoryBubbles;
  END_STRUCT;
  CltChCmd__MultiTask : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_MultiTask;
  END_STRUCT;
  CltChCmd__OpenSSL : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_OpenSSL;
  END_STRUCT;
  CltChCmd__OSKernel : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_OSKernel;
  END_STRUCT;
  CltChCmd__StdLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_StdLib;
  END_STRUCT;
  CltChCmd__SysMsg : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_SysMsg;
  END_STRUCT;
  CltChCmd__TaskObjectControl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_TaskObjectControl;
  END_STRUCT;
  SvrChCmd__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient : STRUCT
    pMeth : ^CMDMETH;
    dData : _TCPIPClient::_FSM_TCPIP_CLIENT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__TCPIPClient : STRUCT
    pCh : ^SvrChCmd__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient;
    dData : _TCPIPClient::_FSM_TCPIP_CLIENT;
    pCmd : ^_TCPIPClient;
  END_STRUCT;
  CltChCmd__TCPIPClient_MQTTClient : STRUCT
    pCh : ^SvrChCmd__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient;
    dData : _TCPIPClient::_FSM_TCPIP_CLIENT;
    pCmd : ^_TCPIPClient_MQTTClient;
  END_STRUCT;
  CltChCmd__TCPIPClientInterface_MQTTClient : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_TCPIPClientInterface_MQTTClient;
  END_STRUCT;
  CltChCmd__XMLReader : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_XMLReader;
  END_STRUCT;
  CltChCmd__XMLStructCreator : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_XMLStructCreator;
  END_STRUCT;
  CltChCmd_AgvConfig : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^AgvConfig;
  END_STRUCT;
  CltChCmd_AgvSettings : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^AgvSettings;
  END_STRUCT;
  CltChCmd_ASCII_BIN : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ASCII_BIN;
  END_STRUCT;
  SvrChCmd_pVoid : STRUCT
    pMeth : ^CMDMETH;
    dData : pVoid;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_CntrlAuxHmi : STRUCT
    pCh : ^SvrChCmd_pVoid;
    dData : pVoid;
    pCmd : ^CntrlAuxHmi;
  END_STRUCT;
  CltChCmd_ComDiagnosis_MQTT : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ComDiagnosis_MQTT;
  END_STRUCT;
  CltChCmd_CriticalSection : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^CriticalSection;
  END_STRUCT;
  CltChCmd_DINT : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrChCmd_ENV_Status : STRUCT
    pMeth : ^CMDMETH;
    dData : ENV_Status;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_EnvironmentVariable : STRUCT
    pCh : ^SvrChCmd_ENV_Status;
    dData : ENV_Status;
    pCmd : ^EnvironmentVariable;
  END_STRUCT;
  CltChCmd_ENVLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ENVLib;
  END_STRUCT;
  CltChCmd_ENVStringAction : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^ENVStringAction;
  END_STRUCT;
  CltChCmd_LinkedObjectBase : STRUCT
    pCh : ^SvrChCmd_pVoid;
    dData : pVoid;
    pCmd : ^LinkedObjectBase;
  END_STRUCT;
  CltChCmd_MerkerEx : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^MerkerEx;
  END_STRUCT;
  SvrChCmd_t_e_WorkerState_PTofCls_MQTTBackgroundWorker : STRUCT
    pMeth : ^CMDMETH;
    dData : MQTTBackgroundWorker::t_e_WorkerState;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_MQTTBackgroundWorker : STRUCT
    pCh : ^SvrChCmd_t_e_WorkerState_PTofCls_MQTTBackgroundWorker;
    dData : MQTTBackgroundWorker::t_e_WorkerState;
    pCmd : ^MQTTBackgroundWorker;
  END_STRUCT;
  SvrChCmd_t_e_MQTTClientStates_PTofCls_MQTTClient : STRUCT
    pMeth : ^CMDMETH;
    dData : MQTTClient::t_e_MQTTClientStates;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_MQTTClient : STRUCT
    pCh : ^SvrChCmd_t_e_MQTTClientStates_PTofCls_MQTTClient;
    dData : MQTTClient::t_e_MQTTClientStates;
    pCmd : ^MQTTClient;
  END_STRUCT;
  SvrChCmd_t_e_MQTTClientStates_PTofCls_MQTTClient_Interface : STRUCT
    pMeth : ^CMDMETH;
    dData : MQTTClient_Interface::t_e_MQTTClientStates;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_MQTTClient_Interface : STRUCT
    pCh : ^SvrChCmd_t_e_MQTTClientStates_PTofCls_MQTTClient_Interface;
    dData : MQTTClient_Interface::t_e_MQTTClientStates;
    pCmd : ^MQTTClient_Interface;
  END_STRUCT;
  CltChCmd_MQTTClient_Interface_Config : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^MQTTClient_Interface_Config;
  END_STRUCT;
  CltChCmd_MqttInterface : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^MqttInterface;
  END_STRUCT;
  CltChCmd_MQTTPacketQueue : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^MQTTPacketQueue;
  END_STRUCT;
  CltChCmd_MQTTTopic_RetVals : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^MQTTTopic_RetVals;
  END_STRUCT;
  CltChCmd_RAMex : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^RAMex;
  END_STRUCT;
  CltChCmd_SigCLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SigCLib;
  END_STRUCT;
  CltChCmd_String : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^String;
  END_STRUCT;
  CltChCmd_StringRAM : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^StringRAM;
  END_STRUCT;
  CltChCmd_Wewo_DynamicBuffer : STRUCT
    pCh : ^SvrChCmd_pVoid;
    dData : pVoid;
    pCmd : ^Wewo_DynamicBuffer;
  END_STRUCT;
  CltChCmd_Wewo_EnumTranslator : STRUCT
    pCh : ^SvrChCmd_pVoid;
    dData : pVoid;
    pCmd : ^Wewo_EnumTranslator;
  END_STRUCT;
  CltChCmd_Wewo_LinkedObjectBase : STRUCT
    pCh : ^SvrChCmd_pVoid;
    dData : pVoid;
    pCmd : ^Wewo_LinkedObjectBase;
  END_STRUCT;
  CltChCmd_WewoBase : STRUCT
    pCh : ^SvrChCmd_pVoid;
    dData : pVoid;
    pCmd : ^WewoBase;
  END_STRUCT;
  SvrChCmd_t_e_MQTT_TopicState_PTofCls_MQTTTopic : STRUCT
    pMeth : ^CMDMETH;
    dData : MQTTTopic::t_e_MQTT_TopicState;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_WewoMqtt : STRUCT
    pCh : ^SvrChCmd_t_e_MQTT_TopicState_PTofCls_MQTTTopic;
    dData : MQTTTopic::t_e_MQTT_TopicState;
    pCmd : ^WewoMqtt;
  END_STRUCT;
  CltChCmd_WewoStringUtils : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^WewoStringUtils;
  END_STRUCT;
  SvrCh__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient : STRUCT
    pMeth : ^CHMETH;
    dData : _TCPIPClient::_FSM_TCPIP_CLIENT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__STATE_TCPIPC_INTF_PTofCls__TCPIPClientInterface : STRUCT
    pMeth : ^CHMETH;
    dData : _TCPIPClientInterface::_STATE_TCPIPC_INTF;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__XML_PARSE_ERROR_PTofCls__XMLReader : STRUCT
    pMeth : ^CHMETH;
    dData : _XMLReader::_XML_PARSE_ERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_gt_AgvMainState : STRUCT
    pMeth : ^CHMETH;
    dData : gt_AgvMainState;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_gt_FifoBufMode : STRUCT
    pMeth : ^CHMETH;
    dData : gt_FifoBufMode;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_gt_LogCmd : STRUCT
    pMeth : ^CHMETH;
    dData : gt_LogCmd;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_gt_LogLevel : STRUCT
    pMeth : ^CHMETH;
    dData : gt_LogLevel;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_gt_LogTarget : STRUCT
    pMeth : ^CHMETH;
    dData : gt_LogTarget;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_gt_ObjectStatus : STRUCT
    pMeth : ^CHMETH;
    dData : gt_ObjectStatus;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_HmiErrorMessages_PTofCls_I_Hmi : STRUCT
    pMeth : ^CHMETH;
    dData : I_Hmi::HmiErrorMessages;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_pChar : STRUCT
    pMeth : ^CHMETH;
    dData : pChar;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_pVoid : STRUCT
    pMeth : ^CHMETH;
    dData : pVoid;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_MQTT_TopicType_PTofCls_MQTTTopic : STRUCT
    pMeth : ^CHMETH;
    dData : MQTTTopic::t_e_MQTT_TopicType;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_READSTEPS_PTofCls__JSONReader : STRUCT
    pMeth : ^CHMETH;
    dData : _JSONReader::t_e_READSTEPS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_WRITESTEPS_PTofCls__JSONWriter : STRUCT
    pMeth : ^CHMETH;
    dData : _JSONWriter::t_e_WRITESTEPS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_XML_READ_STATE_PTofCls__XMLReader : STRUCT
    pMeth : ^CHMETH;
    dData : _XMLReader::XML_READ_STATE;
    pDsc : ^SVRDSC;
  END_STRUCT;
END_TYPE
